openapi: 3.0.0
servers:
  - url: 'http://192.168.21.99:38081/abyss'
  - url: 'http://192.168.10.46:38081/abyss' 
  - url: 'https://apiportal.com/abyss'
info:
  description: Abyss platform APIs
  version: 1.0.0
  title: Abyss
  termsOfService: 'https://apiportal.com/terms/'
  contact:
    email: info@apiportal.com
    name: Abyss
    url: 'https://apiportal.com'
  license:
    name: Abyss 1.0
    url: 'https://apiportal.com/licenses/LICENSE-1.0.html'
tags:
  - name: TODO
    externalDocs:
      url: 'https://apiportal.com'
      description: Find out more
    description: Abyss ... [TODO]  
paths:
  /api-api-tags:
    get:
      tags:
        - TODO
      summary: Get list of apiApiTags
      description: 'Returns list of apiApiTags'
      operationId: getApiApiTags
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfApiApiTag'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    post:
      tags:
        - TODO
      summary: Add a new ApiApiTag
      description: 'Provide a new ApiApiTag to be inserted'
      operationId: addApiApiTags
      responses:
        '201':
          $ref: '#/components/responses/201'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ApiApiTag'
    put:
      tags:
        - TODO
      summary: Update a bulk of ApiApiTag
      description: 'Provide an altered ApiApiTag array to be updated'
      operationId: updateApiApiTags
      parameters:
        - name: uuid
          in: path
          description: bulk of uuids of apiApiTags that need to be updated
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfApiApiTag'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfApiApiTag'          
    delete:
      tags:
        - TODO
      summary: Delete all apiApiTags
      description: 'Deletes all apiApiTags'
      operationId: deleteApiApiTags
      responses:
        '204':
          $ref: '#/components/responses/204'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
  /api-api-tags/{uuid}:
    get:
      tags:
        - TODO
      summary: Get an existing ApiApiTag by uuid
      description: 'Provide an uuid of ApiApiTag to be get'
      operationId: getApiApiTag
      parameters:
        - name: uuid
          in: path
          description: uuid of ApiApiTag that need to be get
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    put:
      tags:
        - TODO
      summary: Update an existing ApiApiTag
      description: 'Provide an altered ApiApiTag to be updated'
      operationId: updateApiApiTag
      parameters:
        - name: uuid
          in: path
          description: uuid of ApiApiTag that need to be updated
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ApiApiTag'
    delete:
      tags:
        - TODO
      summary: Delete ApiApiTag
      description: 'Provide an uuid parameter of ApiApiTag to be updated'
      operationId: deleteApiApiTag
      parameters:
        - name: uuid
          in: path
          description: The uuid of ApiApiTag that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
externalDocs:
  description: See Abyss example
  url: 'https://apiportal.com/apidocs/index.html'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - usermessage
      properties:
        code:
          type: integer
          format: int32
        usermessage:
          type: string
        internalmessage:
          type: string
        details:
          type: string
        recommendation:
          type: string
        moreinfo:
          type: string
          format: uri
    ApiApiTag:
      type: object
      properties:
        apiId:
          type: integer
          format: int32
          description: FK ID of API for many to many relationship of API tags
        apiTagId:
          type: integer
          format: int32
          description: FK ID of API tags for many to many relationship of API tags
  requestBodies:
    ApiApiTag:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiApiTag'          
      description: ApiApiTag object that needs to be added
      required: true
    ListOfApiApiTag:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiApiTag'          
      description: ApiApiTag array that needs to be added
      required: true
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiApiTag'
    '200-ListOfApiApiTag':
      description: A ApiApiTag array
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiApiTag'          
            
    '201':
      description: New ApiApiTag resource has been created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiApiTag'
    '204':
      description: The ApiApiTag resource was successfully deleted
    '304':
      description: Not Modified – The client can use cached data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiApiTag'
    '400':
      description: Invalid UUID supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden – The server understood the request, but is refusing it or the access is not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not found – There is no resource behind the URI
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '405':
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '422':
      description: Unprocessable Entity – server cannot process the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '429':
      description: Too many request(rate limiting)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    default:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: abyss.session
      in: cookie
  links: {}
  callbacks: {}
security:
  - cookieAuth: []
