openapi: 3.0.0
servers:
  - url: 'http://192.168.21.99:38081/abyss'
  - url: 'http://192.168.21.139:38081/abyss'  
  - url: 'http://192.168.10.46:38081/abyss' 
  - url: 'https://apiportal.com/abyss'
info:
  description: Abyss platform APIs
  version: 1.0.0
  title: Abyss
  termsOfService: 'https://apiportal.com/terms/'
  contact:
    email: info@apiportal.com
    name: Abyss
    url: 'https://apiportal.com'
  license:
    name: Abyss 1.0
    url: 'https://apiportal.com/licenses/LICENSE-1.0.html'
tags:
  - name: TODO
    externalDocs:
      url: 'https://apiportal.com'
      description: Find out more
    description: Abyss ... [TODO]  
paths:
  /api-categories:
    get:
      tags:
        - TODO
      summary: Get list of apiCategories
      description: 'Returns list of apiCategories'
      operationId: getApiCategorys
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfApiCategory'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    post:
      tags:
        - TODO
      summary: Add a new ApiCategory
      description: 'Provide a new ApiCategory to be inserted'
      operationId: addApiCategorys
      responses:
        '201':
          $ref: '#/components/responses/201'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ApiCategory'
    put:
      tags:
        - TODO
      summary: Update a bulk of ApiCategory
      description: 'Provide an altered ApiCategory array to be updated'
      operationId: updateApiCategorys
      parameters:
        - name: uuid
          in: path
          description: bulk of uuids of apiCategories that need to be updated
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid          
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfApiCategory'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfApiCategory'          
    delete:
      tags:
        - TODO
      summary: Delete all apiCategories
      description: 'Deletes all apiCategories'
      operationId: deleteApiCategorys
      responses:
        '204':
          $ref: '#/components/responses/204'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
  /api-categories/{uuid}:
    get:
      tags:
        - TODO
      summary: Get an existing ApiCategory by uuid
      description: 'Provide an uuid of ApiCategory to be get'
      operationId: getApiCategory
      parameters:
        - name: uuid
          in: path
          description: uuid of ApiCategory that need to be get
          required: true
          schema:
            type: string
            format: uuid          
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    put:
      tags:
        - TODO
      summary: Update an existing ApiCategory
      description: 'Provide an altered ApiCategory to be updated'
      operationId: updateApiCategory
      parameters:
        - name: uuid
          in: path
          description: uuid of ApiCategory that need to be updated
          required: true
          schema:
            type: string
            format: uuid          
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ApiCategory'
    delete:
      tags:
        - TODO
      summary: Delete ApiCategory
      description: 'Provide an uuid parameter of ApiCategory to be updated'
      operationId: deleteApiCategory
      parameters:
        - name: uuid
          in: path
          description: The uuid of ApiCategory that needs to be deleted
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
externalDocs:
  description: See Abyss example
  url: 'https://apiportal.com/apidocs/index.html'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - usermessage
      properties:
        code:
          type: integer
          format: int32
        usermessage:
          type: string
        internalmessage:
          type: string
        details:
          type: string
        recommendation:
          type: string
        moreinfo:
          type: string
          format: uri
    ApiCategory:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
          description: Secondary primary key. Used in front end messages for security reasons.
        organizationId:
          type: integer
          format: int32
          description: Id of Organization
        created:
          type: string
          readOnly: true
          description: Timestamp of creation #readOnly#
        updated:
          type: string
          readOnly: true
          description: Timestamp of update #readOnly#
        deleted:
          type: string
          readOnly: true
          description: Timestamp of deletion #readOnly#
        isDeleted:
          type: boolean
          readOnly: true
          description: Is record logically deleted #readOnly#
        crudSubjectId:
          type: integer
          format: int32
          description: ID of Subject that reads, creates, updates or deletes
        name:
          type: string
          description: Name of tag
        description:
          type: string
          description: Description of group
  requestBodies:
    ApiCategory:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiCategory'          
      description: ApiCategory object that needs to be added
      required: true
    ListOfApiCategory:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiCategory'          
      description: ApiCategory array that needs to be added
      required: true
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiCategory'
    '200-ListOfApiCategory':
      description: A ApiCategory array
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiCategory'          
            
    '201':
      description: New ApiCategory resource has been created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiCategory'
    '204':
      description: The ApiCategory resource was successfully deleted
    '304':
      description: Not Modified – The client can use cached data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiCategory'
    '400':
      description: Invalid UUID supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden – The server understood the request, but is refusing it or the access is not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not found – There is no resource behind the URI
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '405':
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '422':
      description: Unprocessable Entity – server cannot process the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '429':
      description: Too many request(rate limiting)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    default:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: abyss.session
      in: cookie
  links: {}
  callbacks: {}
security:
  - cookieAuth: []
