openapi: 3.0.0
servers:
  - url: 'http://192.168.21.99:38083/abyss/oapi'
  - url: 'http://192.168.21.139:38083/abyss/oapi'
  - url: 'http://192.168.10.46:38083/abyss/oapi' 
  - url: 'https://apiportal.com/abyss/oapi'
info:
  description: Abyss platform APIs
  version: 1.0.0
  title: Abyss
  termsOfService: 'https://apiportal.com/terms/'
  contact:
    email: info@apiportal.com
    name: Abyss
    url: 'https://apiportal.com'
  license:
    name: Abyss 1.0
    url: 'https://apiportal.com/licenses/LICENSE-1.0.html'
tags:
  - name: TODO
    externalDocs:
      url: 'https://apiportal.com'
      description: Find out more
    description: Abyss ... [TODO]  
paths:
  /subjects:
    get:
      tags:
        - TODO
      summary: Get list of Subjects
      description: 'Returns list of Subjects'
      operationId: getSubjects
      parameters:
        - name: byname
          in: query
          required: false
          schema:
            type: string
          description: search Subjects which names exact match
        - name: likename
          in: query
          required: false
          schema:
            type: string
          description: search Subjects which names begin with
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfSubject'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    post:
      tags:
        - TODO
      summary: Add a bulk of Subjects
      description: 'Provide a list of Subject objects to be inserted'
      operationId: addSubjects
      responses:
        '207':
          $ref: '#/components/responses/207'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfSubject'
    put:
      tags:
        - TODO
      summary: Update a bulk of Subjects
      description: 'Provide a bulk list of  Subject objects to be updated'
      operationId: updateSubjects
      responses:
        '207':
          $ref: '#/components/responses/207'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfSubjectObject'
    delete:
      tags:
        - TODO
      summary: Delete all Subjects
      description: 'Deletes all Subjects'
      operationId: deleteSubjects
      responses:
        '204':
          $ref: '#/components/responses/204'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
  /subjects/{uuid}:
    get:
      tags:
        - TODO
      summary: Get an existing Subject by uuid
      description: 'Provide an uuid of Subject to be get'
      operationId: getSubject
      parameters:
        - name: uuid
          in: path
          description: uuid of Subject that need to be get
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    put:
      tags:
        - TODO
      summary: Update an existing Subject
      description: 'Provide an altered Subject to be updated'
      operationId: updateSubject
      parameters:
        - name: uuid
          in: path
          description: uuid of Subject that need to be updated
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/Subject'
    delete:
      tags:
        - TODO
      summary: Delete Subject
      description: 'Provide an uuid parameter of Subject to be updated'
      operationId: deleteSubject
      parameters:
        - name: uuid
          in: path
          description: The uuid of Subject that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
externalDocs:
  description: See Abyss example
  url: 'https://apiportal.com/apidocs/index.html'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - usermessage
      properties:
        code:
          type: integer
          format: int32
        usermessage:
          type: string
        internalmessage:
          type: string
        details:
          type: string
        recommendation:
          type: string
        moreinfo:
          type: string
          format: uri
    MultiStatus:
      type: object
      required:
        - uuid
      properties:
        uuid:
          type: string
          readOnly: true
        response:
          $ref: '#/components/schemas/Subject'
        error:
          $ref: '#/components/schemas/Error'
    Subject:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
          description: Secondary primary key. Used in front end messages for security reasons.
        organizationid:
          type: integer
          format: int32
          description: Id of Organization
        created:
          type: string
          readOnly: true
          description: Timestamp of creation #readOnly#
        updated:
          type: string
          readOnly: true
          description: Timestamp of update #readOnly#
        deleted:
          type: string
          readOnly: true
          description: Timestamp of deletion #readOnly#
        isdeleted:
          type: boolean
          readOnly: true
          description: Is record logically deleted #readOnly#
        crudsubjectid:
          type: integer
          format: int32
          description: ID of Subject that reads, creates, updates or deletes
        isactivated:
          type: boolean
          readOnly: true
          description: Is user activated after signup by validating secondary verification mechanism #readOnly#
        subjecttypeid:
          type: integer
          format: int32
          description: Id of Subject Type
        subjectname:
          type: string
          description: Username of user that is going to be used as credential
        firstname:
          type: string
          description: First name of user
        lastname:
          type: string
          description: Surname of user
        displayname:
          type: string
          description: Display name or alias of user
        email:
          type: string
          format: email
          description: Main contact email of user #email#
        secondaryemail:
          type: string
          format: email
          description: Secondary email of user for recovering account etc. #email#
        effectivestartdate:
          type: string
          description: Effective start date time of user that he or she can start using the platform
        effectiveenddate:
          type: string
          description: Effective end date time of user that he or she can use the platform until
        password:
          type: string
          format: password
          writeOnly: true
          description: Password of user that is going to be used as credential #Level:1# #writeOnly#
        picture:
          type: string
          format: byte
          description: Picture of subject #base64#
        totallogincount:
          type: integer
          format: int32
          readOnly: true
          description: Total Login Count of Subject #readOnly#
        failedlogincount:
          type: integer
          format: int32
          readOnly: true
          description: Failed Login Count of Subject #readOnly#
        invalidpasswordattemptcount:
          type: integer
          format: int32
          readOnly: true
          description: Invalid Password Attempt Count of Subject #readOnly#
        ispasswordchangerequired:
          type: boolean
          readOnly: true
          description: Does subject have to change password #readOnly#
        passwordexpiresat:
          type: string
          readOnly: true
          description: Password expire date time. After this time subject must change password is still logon else should reset password to get a new one. #readOnly#
        lastloginat:
          type: string
          readOnly: true
          description: Last login date time of subject #readOnly#
        lastpasswordchangeat:
          type: string
          readOnly: true
          description: Last password change date time #readOnly#
        lastauthenticatedat:
          type: string
          readOnly: true
          description: Last successful authentication date time #readOnly#
        lastfailedloginat:
          type: string
          readOnly: true
          description: Last failed login attempt date time #readOnly#
        subjectdirectoryid:
          type: integer
          format: int32
          description: FK ID of Subject Directory
  requestBodies:
    Subject:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subject'          
      description: Subject object that needs to be added or updated
      required: true
    ListOfSubject:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Subject'          
      description: Subject array that needs to be added
      required: true
    ListOfSubjectObject:
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
      description:  list of Subject objects that needs to be updated, each additional property name should be the uuid of coresponding Subject record
      required: true
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subject'
    '200-ListOfSubject':
      description: A Subject array
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Subject'
    '201':
      description: New Subject resource has been created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subject'
    '204':
      description: The Subject resource was successfully deleted
    '207':
      description: Multi Status for bulk operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/MultiStatus'
    '304':
      description: Not Modified – The client can use cached data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subject'
    '400':
      description: Invalid UUID supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden – The server understood the request, but is refusing it or the access is not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not found – There is no resource behind the URI
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '405':
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '422':
      description: Unprocessable Entity – server cannot process the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '429':
      description: Too many request(rate limiting)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    default:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return
  securitySchemes:
    abyssCookieAuth:
      $ref: 'AbyssSecuritySchemes.yaml#/securitySchemes/abyssCookieAuth'
    abyssHttpBasicAuth:
      $ref: 'AbyssSecuritySchemes.yaml#/securitySchemes/abyssHttpBasicAuth'
    abyssApiKeyAuth:
      $ref: 'AbyssSecuritySchemes.yaml#/securitySchemes/abyssApiKeyAuth'
    abyssJWTBearerAuth:
      $ref: 'AbyssSecuritySchemes.yaml#/securitySchemes/abyssJWTBearerAuth'
  links: {}
  callbacks: {}
security:
  - abyssCookieAuth: []
  - abyssHttpBasicAuth: []
  - abyssApiKeyAuth: []
  - abyssJWTBearerAuth: []
