openapi: 3.0.0
servers:
- url: 'http://192.168.21.99:38083/abyss/oapi'
- url: 'http://192.168.21.139:38083/abyss/oapi'
- url: 'http://192.168.10.46:38083/abyss/oapi'
- url: '/abyss/oapi'
info:
  description: 'Abyss platform APIs'
  version: '1.0.0'
  title: 'Abyss'
  termsOfService: 'https://apiportal.com/terms/'
  contact:
    email: 'info@apiportal.com'
    name: 'Abyss'
    url: 'https://apiportal.com'
  license:
    name: 'Abyss 1.0'
    url: 'https://apiportal.com/licenses/LICENSE-1.0.html'
tags:
- name: SubjectGroups
  externalDocs:
    url: 'https://apiportal.com'
    description: 'Find out more'
  description: 'Abyss plaftorm APIs : SubjectGroups crud operations'
- name: SubjectGroup
  externalDocs:
    url: 'https://apiportal.com'
    description: 'Find out more'
  description: 'Abyss plaftorm APIs : SubjectGroup crud operations'
paths:
  /subject-groups:
    get:
      tags:
      - SubjectGroups
      summary: 'Get list of SubjectGroups'
      description: 'Returns list of SubjectGroups'
      operationId: getSubjectGroups
      parameters:
      - name: byname
        in: query
        required: false
        schema:
          type: string
        description: 'search SubjectGroups which names exact match'
      - name: likename
        in: query
        required: false
        schema:
          type: string
        description: 'search SubjectGroups which names begin with'
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          $ref: '#/components/responses/200-ListOfSubjectGroup'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    post:
      tags:
      - SubjectGroups
      summary: 'Add a bulk of SubjectGroups'
      description: 'Provide a list of SubjectGroups to be inserted'
      operationId: addSubjectGroups
      responses:
        '207':
          $ref: '#/components/responses/207'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfSubjectGroup'
    put:
      tags:
      - SubjectGroups
      summary: 'Update a bulk of SubjectGroups'
      description: 'Provide a bulk list of  SubjectGroups to be updated'
      operationId: updateSubjectGroups
      responses:
        '207':
          $ref: '#/components/responses/207'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/ListOfSubjectGroupObject'
    delete:
      tags:
      - SubjectGroups
      summary: 'Delete all SubjectGroups'
      description: 'Deletes all SubjectGroups'
      operationId: deleteSubjectGroups
      responses:
        '204':
          $ref: '#/components/responses/204'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
  /subject-groups/{uuid}:
    get:
      tags:
      - SubjectGroup
      summary: 'Get an existing SubjectGroup by uuid'
      description: 'Provide an uuid of SubjectGroup to be get'
      operationId: getSubjectGroup
      parameters:
      - name: uuid
        in: path
        description: 'uuid of SubjectGroup that need to be get'
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
    put:
      tags:
      - SubjectGroup
      summary: 'Update an existing SubjectGroup'
      description: 'Provide an altered SubjectGroup to be updated'
      operationId: updateSubjectGroup
      parameters:
      - name: uuid
        in: path
        description: 'uuid of SubjectGroup that need to be updated'
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      requestBody:
        $ref: '#/components/requestBodies/SubjectGroup'
    delete:
      tags:
      - SubjectGroup
      summary: 'Delete SubjectGroup'
      description: 'Provide an uuid parameter of SubjectGroup to be updated'
      operationId: deleteSubjectGroup
      parameters:
      - name: uuid
        in: path
        description: 'The uuid of SubjectGroup that needs to be deleted'
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
externalDocs:
  description: 'See Abyss example'
  url: 'https://apiportal.com/apidocs/index.html'
components:
  schemas:
    Error:
      type: object
      required:
      - code
      - usermessage
      properties:
        code:
          type: integer
          format: int32
        usermessage:
          type: string
        internalmessage:
          type: string
        details:
          type: string
        recommendation:
          type: string
        moreinfo:
          type: string
          format: uri
    MultiStatus:
      type: object
      required:
      - uuid
      properties:
        uuid:
          type: string
          readOnly: true
          description: 'uuid of the record'
        status:
          type: integer
          readOnly: true
          description: 'status -Http response code status (2XX, 3XX, 4XX, 5XX)'
        response:
          $ref: '#/components/schemas/SubjectGroup'
        error:
          $ref: '#/components/schemas/Error'
    SubjectGroup:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
          description: 'Secondary primary key. Used in front end messages for security reasons.'
        organizationid:
          type: string
          description: 'Id of Organization'
        created:
          type: string
          readOnly: true
          description: 'Timestamp of creation #readOnly#'
        updated:
          type: string
          readOnly: true
          description: 'Timestamp of update #readOnly#'
        deleted:
          type: string
          readOnly: true
          description: 'Timestamp of deletion #readOnly#'
        isdeleted:
          type: boolean
          readOnly: true
          description: 'Is record logically deleted #readOnly#'
        crudsubjectid:
          type: string
          description: 'ID of Subject that reads, creates, updates or deletes'
        isenabled:
          type: boolean
          description: 'Enabled flag of group'
        groupname:
          type: string
          description: 'Name of group'
        description:
          type: string
          description: 'Description of group'
        effectivestartdate:
          type: string
          description: 'Effective start date time of group that it is active'
        effectiveenddate:
          type: string
          description: 'Effective end date time of group that is active until'
        subjectdirectoryid:
          type: string
          description: 'FK ID of Subject Directory'
  requestBodies:
    SubjectGroup:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubjectGroup'
      description: 'SubjectGroup object that needs to be added or updated'
      required: true
    ListOfSubjectGroup:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SubjectGroup'
      description: 'SubjectGroup array that needs to be added'
      required: true
    ListOfSubjectGroupObject:
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
      description:  'list of SubjectGroup objects that needs to be updated, each additional property name should be the uuid of coresponding SubjectGroup record'
      required: true
  responses:
    '200':
      description: 'Successful operation'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubjectGroup'
    '200-ListOfSubjectGroup':
      description: 'A SubjectGroup array'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SubjectGroup'
    '201':
      description: 'New SubjectGroup resource has been created'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubjectGroup'
    '204':
      description: 'The SubjectGroup resource was successfully deleted'
    '207':
      description: 'Multi Status for bulk operation'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/MultiStatus'
    '304':
      description: 'Not Modified – The client can use cached data'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubjectGroup'
    '400':
      description: 'Invalid UUID supplied'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: 'Authorization information is missing or invalid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: 'Forbidden – The server understood the request, but is refusing it or the access is not allowed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: 'Not found – There is no resource behind the URI'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '405':
      description: 'Method not allowed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '422':
      description: 'Unprocessable Entity – server cannot process the request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '429':
      description: 'Too many request(rate limiting)'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: 'Internal server error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    default:
      description: 'error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: 'The number of items to skip before starting to collect the result set'
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: 'The numbers of items to return'
  securitySchemes:
    abyssCookieAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssCookieAuth'
    abyssHttpBasicAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssHttpBasicAuth'
    abyssApiKeyAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssApiKeyAuth'
    abyssJWTBearerAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssJWTBearerAuth'
    abyssAppAccessTokenAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssAppKeyAuth'
    abyssAppAccessTokenCookieAuth:
      $ref: '/openapi/AbyssSecuritySchemes.yaml#/securitySchemes/abyssAppKeyCookieAuth'
  links: {}
  callbacks: {}
security:
- abyssCookieAuth: []
- abyssHttpBasicAuth: []
- abyssApiKeyAuth: []
- abyssJWTBearerAuth: []
- abyssAppAccessTokenAuth: []
- abyssAppAccessTokenCookieAuth: []
